// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZH2qwEaHbuR9IlUpIfvXcULp47hxzvsc',
    appId: '1:426288156457:web:113810dbd37544261fb138',
    messagingSenderId: '426288156457',
    projectId: 'dummy-bcbb2',
    authDomain: 'dummy-bcbb2.firebaseapp.com',
    storageBucket: 'dummy-bcbb2.appspot.com',
    measurementId: 'G-7KH5Q93BS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzgc8yc2gjXFucbtXEJu7nDv45_mW8PhE',
    appId: '1:426288156457:android:ca7a2f7e8defeea21fb138',
    messagingSenderId: '426288156457',
    projectId: 'dummy-bcbb2',
    storageBucket: 'dummy-bcbb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSuZy7DjHHLJn_4XxXFm1wJ_omWHaEu6o',
    appId: '1:426288156457:ios:91f0896c2766479e1fb138',
    messagingSenderId: '426288156457',
    projectId: 'dummy-bcbb2',
    storageBucket: 'dummy-bcbb2.appspot.com',
    iosBundleId: 'com.example.untitled6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSuZy7DjHHLJn_4XxXFm1wJ_omWHaEu6o',
    appId: '1:426288156457:ios:a6fd1b7356fdda2b1fb138',
    messagingSenderId: '426288156457',
    projectId: 'dummy-bcbb2',
    storageBucket: 'dummy-bcbb2.appspot.com',
    iosBundleId: 'com.example.untitled6.RunnerTests',
  );
}
